DROP TABLE IF EXISTS client CASCADE;
DROP TABLE IF EXISTS client_payment CASCADE;
DROP TABLE IF EXISTS client_address CASCADE;
DROP TABLE IF EXISTS client_deferred_product CASCADE;
DROP TABLE IF EXISTS client_shopped_product CASCADE;
DROP TABLE IF EXISTS client_ordered_product CASCADE;
DROP TABLE IF EXISTS order_details CASCADE;
DROP TABLE IF EXISTS order_product CASCADE;
DROP TABLE IF EXISTS product CASCADE;
DROP TABLE IF EXISTS product_feedback CASCADE;
DROP TABLE IF EXISTS product_video CASCADE;
DROP TABLE IF EXISTS product_photo CASCADE;
DROP TABLE IF EXISTS product_special_condition CASCADE;
DROP TABLE IF EXISTS product_category CASCADE;
DROP TABLE IF EXISTS delivery_details CASCADE;
DROP TABLE IF EXISTS address CASCADE;
DROP TABLE IF EXISTS payment_details CASCADE;
DROP TABLE IF EXISTS payment_method CASCADE;

DROP SEQUENCE IF EXISTS client_seq;
DROP SEQUENCE IF EXISTS client_payment_seq;
DROP SEQUENCE IF EXISTS client_address_seq;
DROP SEQUENCE IF EXISTS client_deferred_product_seq;
DROP SEQUENCE IF EXISTS client_shopped_product_seq;
DROP SEQUENCE IF EXISTS client_ordered_product_seq;
DROP SEQUENCE IF EXISTS order_details_seq;
DROP SEQUENCE IF EXISTS order_product_seq;
DROP SEQUENCE IF EXISTS product_seq;
DROP SEQUENCE IF EXISTS product_feedback_seq;
DROP SEQUENCE IF EXISTS product_video_seq;
DROP SEQUENCE IF EXISTS product_photo_seq;
DROP SEQUENCE IF EXISTS product_special_condition_seq;
DROP SEQUENCE IF EXISTS product_category_seq;
DROP SEQUENCE IF EXISTS delivery_details_seq;
DROP SEQUENCE IF EXISTS address_seq;
DROP SEQUENCE IF EXISTS payment_details_seq;
DROP SEQUENCE IF EXISTS payment_method_seq;

DROP TYPE IF EXISTS available_payment_method;
DROP TYPE IF EXISTS available_payment_status;
DROP TYPE IF EXISTS available_delivery_method;
DROP TYPE IF EXISTS available_delivery_status;