insert into product_category ( title, parent_id) values ('donec ut', null);
insert into product_category ( title, parent_id) values ('in lacus', null);
insert into product_category ( title, parent_id) values ('rutrum nulla nunc', null);
insert into product_category ( title, parent_id) values ('vulputate', null);
insert into product_category ( title, parent_id) values ('justo etiam pretium', null);
insert into product_category ( title, parent_id) values ('sit amet diam', null);
insert into product_category ( title, parent_id) values ('fermentum justo', null);
insert into product_category ( title, parent_id) values ('ligula vehicula', null);
insert into product_category ( title, parent_id) values ('lectus in', null);
insert into product_category ( title, parent_id) values ( 'platea dictumst aliquam', null);
insert into product_category ( title, parent_id) values ( 'tincidunt', null);
insert into product_category ( title, parent_id) values ( 'pulvinar lobortis', 10);
insert into product_category ( title, parent_id) values ( 'lobortis', null);
insert into product_category ( title, parent_id) values ( 'porta volutpat erat', 12);
insert into product_category ( title, parent_id) values ( 'feugiat non pretium', 13);
insert into product_category ( title, parent_id) values ( 'eros', 14);
insert into product_category ( title, parent_id) values ( 'eros viverra eget', null);
insert into product_category ( title, parent_id) values ( 'pede', 16);
insert into product_category ( title, parent_id) values ( 'in hac habitasse', 17);
insert into product_category ( title, parent_id) values ( 'curabitur convallis', 18);









insert into product_photo ( url, parent_id) values ('https://home-depot/photo/evwzpozvfkkhddoppkpz',  null);
insert into product_photo ( url, parent_id) values ('https://home-depot/photo/udrckirgcayhttbaafkw',  null);
insert into product_photo ( url, parent_id) values ('https://home-depot/photo/osiljtmgitmbluotjqxc',  null);
insert into product_photo ( url, parent_id) values ('https://home-depot/photo/pdrynypahkpfznuwxinh',  null);
insert into product_photo ( url, parent_id) values ('https://home-depot/photo/lemjfjhtkvhcqazdcjoo',  null);
insert into product_photo ( url, parent_id) values ('https://home-depot/photo/qbetyaactpxedawmdhbb',  null);
insert into product_photo ( url, parent_id) values ('https://home-depot/photo/tslniefhmeflnktxmxdg',  null);
insert into product_photo ( url, parent_id) values ('https://home-depot/photo/rqbbnbzbhpotjdfpqjaf',  null);
insert into product_photo ( url, parent_id) values ('https://home-depot/photo/qjbgyewqspkpdwjvlcug',  null);
insert into product_photo ( url, parent_id) values ( 'https://home-depot/photo/rbuxjrsjvajdijwpdxkg', null);
insert into product_photo ( url, parent_id) values ( 'https://home-depot/photo/btzawqirdwqmpiwyhbhx', null);
insert into product_photo ( url, parent_id) values ( 'https://home-depot/photo/tyoiqwqxwkadbdcdsmnf', null);
insert into product_photo ( url, parent_id) values ( 'https://home-depot/photo/vhfodmtthubhwmkultkl', null);
insert into product_photo ( url, parent_id) values ( 'https://home-depot/photo/bsglbcqnsjctpforvmkg', null);
insert into product_photo ( url, parent_id) values ( 'https://home-depot/photo/cepanmrhsvzzsjqeudvu', null);
insert into product_photo ( url, parent_id) values ( 'https://home-depot/photo/wbxznsnxblaibgqinscb', null);
insert into product_photo ( url, parent_id) values ( 'https://home-depot/photo/etbulpenolnwxwuaxrws', null);
insert into product_photo ( url, parent_id) values ( 'https://home-depot/photo/eujrqcnvfpebklqcchqs', null);
insert into product_photo ( url, parent_id) values ( 'https://home-depot/photo/akeyrydynkgbppequusk', null);
insert into product_photo ( url, parent_id) values ( 'https://home-depot/photo/rstegoyoybrfmuhaswrs', null);
insert into product_photo ( url, parent_id) values ( 'https://home-depot/photo/eetryvnmzjbrnmynjvux', null);
insert into product_photo ( url, parent_id) values ( 'https://home-depot/photo/gnmdtdakasvbykeezfix', null);
insert into product_photo ( url, parent_id) values ( 'https://home-depot/photo/atpglntqmffaepaxjgxc', null);
insert into product_photo ( url, parent_id) values ( 'https://home-depot/photo/pnifimuddedtpgpvrets', null);
insert into product_photo ( url, parent_id) values ( 'https://home-depot/photo/lenjjczzhyxylaqhltsv', null);
insert into product_photo ( url, parent_id) values ( 'https://home-depot/photo/akdoytittxsekvhkcrbq', null);
insert into product_photo ( url, parent_id) values ( 'https://home-depot/photo/mhglchcoyaqxafmhtirv', null);
insert into product_photo ( url, parent_id) values ( 'https://home-depot/photo/zplikptzpkqbtmmhjjls', null);
insert into product_photo ( url, parent_id) values ( 'https://home-depot/photo/kedjbkfxyfqyztjcbkbj', null);
insert into product_photo ( url, parent_id) values ( 'https://home-depot/photo/imqbgvfsllkusiaontmm', null);
insert into product_photo ( url, parent_id) values ( 'https://home-depot/photo/jwcdthdgwmyoojscklcf', null);
insert into product_photo ( url, parent_id) values ( 'https://home-depot/photo/fuyatktuenjpmfeapnoy', 10);
insert into product_photo ( url, parent_id) values ( 'https://home-depot/photo/ucrqprpezflolclndhkj', 12);
insert into product_photo ( url, parent_id) values ( 'https://home-depot/photo/vdobxehddnaqhhcoqtbt', 14);
insert into product_photo ( url, parent_id) values ( 'https://home-depot/photo/aqfyrutaxooxcuzfjjim', 16);
insert into product_photo ( url, parent_id) values ( 'https://home-depot/photo/ohyxdcvyemzpkpvreqeo', null);
insert into product_photo ( url, parent_id) values ( 'https://home-depot/photo/ceqraefozkchsbljiuyu', 20);
insert into product_photo ( url, parent_id) values ( 'https://home-depot/photo/fqsyulljkehtutqxwqiy', 22);
insert into product_photo ( url, parent_id) values ( 'https://home-depot/photo/rencxqwtvidijtxzweik', null);
insert into product_photo ( url, parent_id) values ( 'https://home-depot/photo/uukiginvopdlexpeywev', 26);
insert into product_photo ( url, parent_id) values ( 'https://home-depot/photo/czuzmsiiifdcmclkoxht', null);
insert into product_photo ( url, parent_id) values ( 'https://home-depot/photo/jdpdvkejdfvwciduujvs', null);
insert into product_photo ( url, parent_id) values ( 'https://home-depot/photo/eneswktisckpnluyprrf', 32);
insert into product_photo ( url, parent_id) values ( 'https://home-depot/photo/ybowfmddjesikpuemlgg', 34);
insert into product_photo ( url, parent_id) values ( 'https://home-depot/photo/xnyqvdygkohaaybzfvxb', null);
insert into product_photo ( url, parent_id) values ( 'https://home-depot/photo/ahektuhjqgtvzraxysem', 38);
insert into product_photo ( url, parent_id) values ( 'https://home-depot/photo/chzigcelagxfrlgqemoc', 40);
insert into product_photo ( url, parent_id) values ( 'https://home-depot/photo/lwgibmhimxvtcwrqdvwg', 11);
insert into product_photo ( url, parent_id) values ( 'https://home-depot/photo/etiyubpjzqlveceliovp', 13);
insert into product_photo ( url, parent_id) values ( 'https://home-depot/photo/pscdrnjodhzamcjtjhwc', 15);
insert into product_photo ( url, parent_id) values ( 'https://home-depot/photo/ocjavljxucetxovctpqd', 17);
insert into product_photo ( url, parent_id) values ( 'https://home-depot/photo/warnbocwgzhchnfuqcuw', null);
insert into product_photo ( url, parent_id) values ( 'https://home-depot/photo/rpzmtrgkapuecuckrucf', null);
insert into product_photo ( url, parent_id) values ( 'https://home-depot/photo/rmrndoacwbujpwpownoa', 23);
insert into product_photo ( url, parent_id) values ( 'https://home-depot/photo/jtklctasrrlcskeygpqy', 25);
insert into product_photo ( url, parent_id) values ( 'https://home-depot/photo/nzfrqrhyiltjsrmqgwtl', null);
insert into product_photo ( url, parent_id) values ( 'https://home-depot/photo/hccpujxnafkjjiakdgkx', 29);
insert into product_photo ( url, parent_id) values ( 'https://home-depot/photo/ufxtaptvzaphcpmagtru', 31);
insert into product_photo ( url, parent_id) values ( 'https://home-depot/photo/pgywncbduhbguhnhbwse', 33);
insert into product_photo ( url, parent_id) values ( 'https://home-depot/photo/ogbobpbonxnubodoaknm', 35);
insert into product_photo ( url, parent_id) values ( 'https://home-depot/photo/jkuqkmbegxnkgplvirny', 37);
insert into product_photo ( url, parent_id) values ( 'https://home-depot/photo/kzwkssfnyayedfctufsb', 39);
insert into product_photo ( url, parent_id) values ( 'https://home-depot/photo/jbgskmlmcvlpcrqpbcnv', 10);
insert into product_photo ( url, parent_id) values ( 'https://home-depot/photo/ulvbimerbuilkedybnpe', null);
insert into product_photo ( url, parent_id) values ( 'https://home-depot/photo/pvsbldrvghzwswwipbhx', 14);
insert into product_photo ( url, parent_id) values ( 'https://home-depot/photo/zctqmfwpwyxruojzlcqx', 16);
insert into product_photo ( url, parent_id) values ( 'https://home-depot/photo/siomxziioqthqdghltmr', null);
insert into product_photo ( url, parent_id) values ( 'https://home-depot/photo/jitequwtrxuvxwkzsedl', 20);
insert into product_photo ( url, parent_id) values ( 'https://home-depot/photo/hgqosbmopzcomdfsqand', 22);
insert into product_photo ( url, parent_id) values ( 'https://home-depot/photo/afkmwyaeplrdwztenryo', 24);
insert into product_photo ( url, parent_id) values ( 'https://home-depot/photo/dkllgntksjkwdrixpsjc', 26);
insert into product_photo ( url, parent_id) values ( 'https://home-depot/photo/taomutgwqsntnpyajlac', 28);
insert into product_photo ( url, parent_id) values ( 'https://home-depot/photo/mieegwuxcuonrgtrjrjt', 30);
insert into product_photo ( url, parent_id) values ( 'https://home-depot/photo/akubegqwuvwdaofqyxcc', 32);
insert into product_photo ( url, parent_id) values ( 'https://home-depot/photo/xllkkkblyxnjpbvygmqt', null);
insert into product_photo ( url, parent_id) values ( 'https://home-depot/photo/blhldmrpsecxovvvaoiz', null);
insert into product_photo ( url, parent_id) values ( 'https://home-depot/photo/zdkgptbvqpdqvmqfqwsa', 38);
insert into product_photo ( url, parent_id) values ( 'https://home-depot/photo/iucabrlzlojmtkmbgsxv', 40);
insert into product_photo ( url, parent_id) values ( 'https://home-depot/photo/nistnfejqvjvruevewkr', 11);
insert into product_photo ( url, parent_id) values ( 'https://home-depot/photo/zbbhnwnnuijcmrgtvnht', 13);
insert into product_photo ( url, parent_id) values ( 'https://home-depot/photo/iuradjgawvnlxttwtjfq', 15);
insert into product_photo ( url, parent_id) values ( 'https://home-depot/photo/rqgmeqrmeahqojwerksj', 17);
insert into product_photo ( url, parent_id) values ( 'https://home-depot/photo/lvuscsejwgtyjnmrckvg', 19);
insert into product_photo ( url, parent_id) values ( 'https://home-depot/photo/mogwhhnwgcuszwgzklat', 21);
insert into product_photo ( url, parent_id) values ( 'https://home-depot/photo/lagtmyzcmjstqpkgfdeu', 23);
insert into product_photo ( url, parent_id) values ( 'https://home-depot/photo/kivyqaivwubkwbvjtzat', 25);
insert into product_photo ( url, parent_id) values ( 'https://home-depot/photo/nxczrymzdyrvtqrmsukh', null);
insert into product_photo ( url, parent_id) values ( 'https://home-depot/photo/dfqelyfgghzvseshumpq', 29);
insert into product_photo ( url, parent_id) values ( 'https://home-depot/photo/vcuqodeeudqufmghiqqc', null);
insert into product_photo ( url, parent_id) values ( 'https://home-depot/photo/caxzpbjcroikmsydsceo', 33);
insert into product_photo ( url, parent_id) values ( 'https://home-depot/photo/gzolqmrdhdzosqbosmfw', 35);
insert into product_photo ( url, parent_id) values ( 'https://home-depot/photo/siwkhvwdvzaediwhyebu', 37);
insert into product_photo ( url, parent_id) values ( 'https://home-depot/photo/oluyplybohvgocasmzqv', 39);
insert into product_photo ( url, parent_id) values ( 'https://home-depot/photo/gltgbexgxemwndeoxofp', null);
insert into product_photo ( url, parent_id) values ( 'https://home-depot/photo/libeepgimatpblyrrfjp', null);
insert into product_photo ( url, parent_id) values ( 'https://home-depot/photo/dwnueolcyihahbwpkyma', 14);
insert into product_photo ( url, parent_id) values ( 'https://home-depot/photo/cofqaxmstpyxwqivgmjr', 16);
insert into product_photo ( url, parent_id) values ( 'https://home-depot/photo/mgiwpzntckgcroaewilh', 18);
insert into product_photo ( url, parent_id) values ( 'https://home-depot/photo/jvykhxxoexthgjrxzbln', null);
insert into product_photo ( url, parent_id) values ( 'https://home-depot/photo/ppjyxkijgstdjnuzkyuf', 22);




insert into product ( title, description, photo_id, option, category_id) values ('rutrum', 'lacus at velit', 9, null, 4);
insert into product ( title, description, photo_id, option, category_id) values ('ullamcorper augue a', 'sodales sed tincidunt eu', 88, null, 11);
insert into product ( title, description, photo_id, option, category_id) values ('et magnis dis', 'ut odio cras mi', 37, null, 20);
insert into product ( title, description, photo_id, option, category_id) values ('sed', 'tortor risus dapibus augue vel', 59, null, 16);
insert into product ( title, description, photo_id, option, category_id) values ('sollicitudin mi sit', null, null, null, 13);
insert into product ( title, description, photo_id, option, category_id) values ('sollicitudin vitae consectetuer', null, null, null, 15);
insert into product ( title, description, photo_id, option, category_id) values ('mi integer', null, null, null, 6);
insert into product ( title, description, photo_id, option, category_id) values ('id', 'vestibulum aliquet ultrices erat tortor sollicitudin', 32, null, 7);
insert into product ( title, description, photo_id, option, category_id) values ('risus praesent', 'auctor gravida sem praesent id', 11, null, 2);
insert into product ( title, description, photo_id, option, category_id) values ('viverra diam vitae', 'porttitor pede justo', 40, null, 15);
insert into product ( title, description, photo_id, option, category_id) values ('quam', 'hac habitasse platea dictumst', 27, null, 7);
insert into product ( title, description, photo_id, option, category_id) values ('ullamcorper', 'posuere felis sed lacus morbi sem mauris laoreet', 39, null, 2);
insert into product ( title, description, photo_id, option, category_id) values ('id nisl', null, null, null, 6);
insert into product ( title, description, photo_id, option, category_id) values ('turpis enim blandit', null, null, null, 8);
insert into product ( title, description, photo_id, option, category_id) values ('ultrices erat', 'tincidunt eu felis fusce posuere felis sed', 100, null, 12);
insert into product ( title, description, photo_id, option, category_id) values ('in purus eu', null, null, null, 16);
insert into product ( title, description, photo_id, option, category_id) values ('pede posuere', 'ipsum integer', 26, null, 11);
insert into product ( title, description, photo_id, option, category_id) values ('nulla quisque arcu', null, null, null, 17);
insert into product ( title, description, photo_id, option, category_id) values ('a', 'integer pede justo lacinia eget tincidunt eget tempus vel', 95, null, 13);
insert into product ( title, description, photo_id, option, category_id) values ('vestibulum', 'vulputate ut ultrices vel augue vestibulum ante ipsum primis', 95, null, 8);
insert into product ( title, description, photo_id, option, category_id) values ('tincidunt eget', null, null, null, 1);
insert into product ( title, description, photo_id, option, category_id) values ('tristique est', 'sapien cum', 13, null, 9);
insert into product ( title, description, photo_id, option, category_id) values ('ac neque', 'fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit', 43, null, 10);
insert into product ( title, description, photo_id, option, category_id) values ('augue a suscipit', 'facilisi cras non velit nec', 31, null, 16);
insert into product ( title, description, photo_id, option, category_id) values ('quisque id justo', 'ac diam cras pellentesque volutpat dui maecenas tristique est', 37, null, 19);
insert into product ( title, description, photo_id, option, category_id) values ('dictumst morbi vestibulum', null, null, null, 8);
insert into product ( title, description, photo_id, option, category_id) values ('phasellus in felis', null, null, null, 3);
insert into product ( title, description, photo_id, option, category_id) values ('pede', null, null, null, 18);
insert into product ( title, description, photo_id, option, category_id) values ('lectus in quam', null, null, null, 8);
insert into product ( title, description, photo_id, option, category_id) values ('convallis tortor risus', 'id lobortis convallis tortor risus', 3, null, 12);
insert into product ( title, description, photo_id, option, category_id) values ('vestibulum aliquet', null, null, null, 13);
insert into product ( title, description, photo_id, option, category_id) values ('vel', null, null, null, 16);
insert into product ( title, description, photo_id, option, category_id) values ('turpis enim', 'eget vulputate ut ultrices vel augue vestibulum ante', 55, null, 2);
insert into product ( title, description, photo_id, option, category_id) values ('turpis sed ante', 'ultrices posuere cubilia curae nulla dapibus dolor', 62, null, 4);
insert into product ( title, description, photo_id, option, category_id) values ('faucibus orci luctus', 'ligula sit amet eleifend pede libero quis orci nullam', 28, null, 20);
insert into product ( title, description, photo_id, option, category_id) values ('arcu', 'lorem vitae mattis nibh', 75, null, 15);
insert into product ( title, description, photo_id, option, category_id) values ('in imperdiet et', null, null, null, 9);
insert into product ( title, description, photo_id, option, category_id) values ('ultrices', 'molestie sed justo pellentesque viverra pede ac diam cras', 2, null, 18);
insert into product ( title, description, photo_id, option, category_id) values ('ante vivamus', null, null, null, 16);
insert into product ( title, description, photo_id, option, category_id) values ('justo', 'in ante vestibulum ante ipsum primis in faucibus orci luctus', 43, null, 3);
insert into product ( title, description, photo_id, option, category_id) values ('ipsum primis', 'molestie nibh', 13, null, 2);
insert into product ( title, description, photo_id, option, category_id) values ('rhoncus aliquam', 'amet nulla quisque arcu libero rutrum ac lobortis', 18, null, 6);
insert into product ( title, description, photo_id, option, category_id) values ('habitasse platea dictumst', 'ac nulla sed vel enim', 56, null, 4);
insert into product ( title, description, photo_id, option, category_id) values ('pretium nisl ut', 'quis turpis', 21, null, 18);
insert into product ( title, description, photo_id, option, category_id) values ('at', null, null, null, 10);
insert into product ( title, description, photo_id, option, category_id) values ('consectetuer', null, null, null, 11);
insert into product ( title, description, photo_id, option, category_id) values ('feugiat et', null, null, null, 13);
insert into product ( title, description, photo_id, option, category_id) values ('nunc', null, null, null, 2);
insert into product ( title, description, photo_id, option, category_id) values ('primis', null, null, null, 2);
insert into product ( title, description, photo_id, option, category_id) values ('pede morbi', 'semper porta volutpat', 79, null, 7);
insert into product ( title, description, photo_id, option, category_id) values ('nisl aenean lectus', null, null, null, 7);
insert into product ( title, description, photo_id, option, category_id) values ('quis orci', null, null, null, 2);
insert into product ( title, description, photo_id, option, category_id) values ('pellentesque at nulla', 'eu tincidunt in leo maecenas', 61, null, 1);
insert into product ( title, description, photo_id, option, category_id) values ('vestibulum sit amet', null, null, null, 1);
insert into product ( title, description, photo_id, option, category_id) values ('et', null, null, null, 13);
insert into product ( title, description, photo_id, option, category_id) values ('enim sit amet', null, null, null, 14);
insert into product ( title, description, photo_id, option, category_id) values ('placerat praesent', 'sit amet lobortis sapien sapien non mi integer', 27, null, 17);
insert into product ( title, description, photo_id, option, category_id) values ('ultrices aliquet maecenas', null, null, null, 8);
insert into product ( title, description, photo_id, option, category_id) values ('cubilia', 'quis libero', 71, null, 7);
insert into product ( title, description, photo_id, option, category_id) values ('amet', 'ridiculus mus vivamus vestibulum', 55, null, 16);
insert into product ( title, description, photo_id, option, category_id) values ('dapibus nulla suscipit', null, null, null, 1);
insert into product ( title, description, photo_id, option, category_id) values ('interdum', 'duis bibendum', 21, null, 13);
insert into product ( title, description, photo_id, option, category_id) values ('etiam', null, null, null, 5);
insert into product ( title, description, photo_id, option, category_id) values ('et magnis', 'at nibh in hac habitasse', 98, null, 6);
insert into product ( title, description, photo_id, option, category_id) values ('accumsan felis', null, null, null, 15);
insert into product ( title, description, photo_id, option, category_id) values ('sed vel enim', null, null, null, 6);
insert into product ( title, description, photo_id, option, category_id) values ('sit amet sem', 'justo in blandit ultrices enim lorem ipsum dolor sit', 16, null, 8);
insert into product ( title, description, photo_id, option, category_id) values ('neque', 'eleifend quam a odio', 21, null, 10);
insert into product ( title, description, photo_id, option, category_id) values ('tincidunt eget tempus', null, null, null, 3);
insert into product ( title, description, photo_id, option, category_id) values ('imperdiet sapien', null, null, null, 7);
insert into product ( title, description, photo_id, option, category_id) values ('duis', 'et commodo vulputate justo in blandit ultrices enim lorem ipsum', 36, null, 10);
insert into product ( title, description, photo_id, option, category_id) values ('in congue etiam', null, null, null, 5);
insert into product ( title, description, photo_id, option, category_id) values ('vehicula consequat', 'morbi non quam nec', 11, null, 9);
insert into product ( title, description, photo_id, option, category_id) values ('gravida nisi at', 'mus etiam vel augue vestibulum rutrum', 99, null, 7);
insert into product ( title, description, photo_id, option, category_id) values ('ut rhoncus aliquet', null, null, null, 13);
insert into product ( title, description, photo_id, option, category_id) values ('nec euismod scelerisque', null, null, null, 16);
insert into product ( title, description, photo_id, option, category_id) values ('amet eros suspendisse', null, null, null, 1);
insert into product ( title, description, photo_id, option, category_id) values ('nam', null, null, null, 11);
insert into product ( title, description, photo_id, option, category_id) values ('id', null, null, null, 14);
insert into product ( title, description, photo_id, option, category_id) values ('ut nunc', 'ultrices phasellus id sapien in sapien', 1, null, 14);
insert into product ( title, description, photo_id, option, category_id) values ('ullamcorper purus sit', 'sapien a libero nam dui proin leo odio porttitor', 62, null, 19);
insert into product ( title, description, photo_id, option, category_id) values ('in eleifend', 'ut massa volutpat convallis morbi odio odio elementum eu', 29, null, 12);
insert into product ( title, description, photo_id, option, category_id) values ('orci vehicula condimentum', 'sagittis dui vel nisl duis', 63, null, 15);
insert into product ( title, description, photo_id, option, category_id) values ('mus', null, null, null, 7);
insert into product ( title, description, photo_id, option, category_id) values ('id nisl', null, null, null, 1);
insert into product ( title, description, photo_id, option, category_id) values ('amet sapien', 'platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget', 13, null, 5);
insert into product ( title, description, photo_id, option, category_id) values ('pede lobortis', 'ultrices libero non mattis', 81, null, 20);
insert into product ( title, description, photo_id, option, category_id) values ('erat id', 'tempus vel pede morbi', 43, null, 4);
insert into product ( title, description, photo_id, option, category_id) values ('in', 'maecenas pulvinar lobortis est phasellus sit amet erat nulla', 44, null, 7);
insert into product ( title, description, photo_id, option, category_id) values ('donec quis orci', null, null, null, 1);
insert into product ( title, description, photo_id, option, category_id) values ('justo', 'imperdiet nullam orci pede venenatis non sodales sed tincidunt eu', 63, null, 9);
insert into product ( title, description, photo_id, option, category_id) values ('ipsum ac', 'lacinia aenean sit amet justo morbi ut odio cras', 70, null, 3);
insert into product ( title, description, photo_id, option, category_id) values ('aenean', 'in tempus sit amet sem fusce consequat nulla', 65, null, 2);
insert into product ( title, description, photo_id, option, category_id) values ('dapibus dolor', 'ligula in lacus curabitur at ipsum ac tellus', 38, null, 2);
insert into product ( title, description, photo_id, option, category_id) values ('et ultrices posuere', null, null, null, 2);
insert into product ( title, description, photo_id, option, category_id) values ('pellentesque volutpat', null, null, null, 19);
insert into product ( title, description, photo_id, option, category_id) values ('congue diam', 'est quam pharetra magna ac consequat metus sapien ut nunc', 50, null, 17);
insert into product ( title, description, photo_id, option, category_id) values ('velit donec diam', 'erat quisque erat eros viverra', 45, null, 19);
insert into product ( title, description, photo_id, option, category_id) values ('odio', 'penatibus et magnis dis parturient montes nascetur', 16, null, 2);
insert into product ( title, description, photo_id, option, category_id) values ( 'nisl', null, null, null, 5);
insert into product ( title, description, photo_id, option, category_id) values ( 'sit amet justo', null, null, null, 18);
insert into product ( title, description, photo_id, option, category_id) values ( 'vel accumsan tellus', 'augue aliquam erat volutpat in congue etiam justo etiam pretium', 70, null, 18);
insert into product ( title, description, photo_id, option, category_id) values ( 'et magnis dis', null, null, null, 3);
insert into product ( title, description, photo_id, option, category_id) values ( 'ridiculus mus vivamus', 'luctus rutrum nulla tellus in sagittis dui vel nisl duis', 41, null, 16);
insert into product ( title, description, photo_id, option, category_id) values ( 'dui maecenas tristique', 'orci eget orci vehicula condimentum curabitur', 51, null, 17);
insert into product ( title, description, photo_id, option, category_id) values ( 'est lacinia', 'aenean lectus pellentesque eget nunc donec quis orci eget', 5, null, 2);
insert into product ( title, description, photo_id, option, category_id) values ( 'aenean', 'massa quis augue luctus tincidunt nulla mollis molestie lorem quisque', 10, null, 6);
insert into product ( title, description, photo_id, option, category_id) values ( 'nisi', 'cras in purus', 31, null, 7);
insert into product ( title, description, photo_id, option, category_id) values ( 'viverra pede', 'nulla facilisi', 37, null, 13);
insert into product ( title, description, photo_id, option, category_id) values ( 'curae duis faucibus', 'nulla ac enim in tempor turpis', 83, null, 16);
insert into product ( title, description, photo_id, option, category_id) values ( 'purus', null, null, null, 1);
insert into product ( title, description, photo_id, option, category_id) values ( 'eleifend quam a', 'amet eleifend', 54, null, 2);
insert into product ( title, description, photo_id, option, category_id) values ( 'tristique in', 'in hac habitasse platea dictumst', 86, null, 4);
insert into product ( title, description, photo_id, option, category_id) values ( 'ipsum', 'lobortis vel', 38, null, 12);
insert into product ( title, description, photo_id, option, category_id) values ( 'amet lobortis sapien', null, null, null, 12);
insert into product ( title, description, photo_id, option, category_id) values ( 'massa donec', 'aenean sit amet justo morbi ut odio cras', 20, null, 7);
insert into product ( title, description, photo_id, option, category_id) values ( 'lobortis convallis tortor', 'rutrum nulla tellus', 51, null, 10);
insert into product ( title, description, photo_id, option, category_id) values ( 'dignissim vestibulum vestibulum', 'at dolor quis odio consequat varius', 60, null, 2);
insert into product ( title, description, photo_id, option, category_id) values ( 'nulla sed', 'non velit donec', 36, null, 4);
insert into product ( title, description, photo_id, option, category_id) values ( 'nascetur ridiculus mus', null, null, null, 13);
insert into product ( title, description, photo_id, option, category_id) values ( 'volutpat', null, null, null, 20);
insert into product ( title, description, photo_id, option, category_id) values ( 'vestibulum ante', null, null, null, 10);
insert into product ( title, description, photo_id, option, category_id) values ( 'aliquam', 'morbi non lectus aliquam sit amet diam', 11, null, 14);
insert into product ( title, description, photo_id, option, category_id) values ( 'eget', 'ullamcorper purus', 31, null, 15);
insert into product ( title, description, photo_id, option, category_id) values ( 'amet erat', null, null, null, 9);
insert into product ( title, description, photo_id, option, category_id) values ( 'non lectus aliquam', null, null, null, 11);
insert into product ( title, description, photo_id, option, category_id) values ( 'faucibus accumsan', 'quis augue luctus tincidunt nulla mollis molestie lorem quisque', 75, null, 2);
insert into product ( title, description, photo_id, option, category_id) values ( 'diam', 'eget semper', 13, null, 17);
insert into product ( title, description, photo_id, option, category_id) values ( 'ipsum', 'suspendisse accumsan tortor quis turpis', 2, null, 4);
insert into product ( title, description, photo_id, option, category_id) values ( 'eleifend pede', 'ligula sit amet eleifend', 35, null, 6);
insert into product ( title, description, photo_id, option, category_id) values ( 'consequat', 'etiam justo etiam pretium', 31, null, 20);
insert into product ( title, description, photo_id, option, category_id) values ( 'non interdum in', 'nulla ac enim in tempor turpis nec euismod', 84, null, 10);
insert into product ( title, description, photo_id, option, category_id) values ( 'venenatis', 'sed tristique in tempus sit amet sem fusce', 96, null, 20);
insert into product ( title, description, photo_id, option, category_id) values ( 'at ipsum ac', null, null, null, 18);
insert into product ( title, description, photo_id, option, category_id) values ( 'in tempus sit', null, null, null, 9);
insert into product ( title, description, photo_id, option, category_id) values ( 'est et', null, null, null, 13);
insert into product ( title, description, photo_id, option, category_id) values ( 'vestibulum', null, null, null, 6);
insert into product ( title, description, photo_id, option, category_id) values ( 'primis in faucibus', null, null, null, 12);
insert into product ( title, description, photo_id, option, category_id) values ( 'aliquet at feugiat', 'curae donec pharetra magna vestibulum aliquet ultrices', 64, null, 11);
insert into product ( title, description, photo_id, option, category_id) values ( 'primis', null, null, null, 12);
insert into product ( title, description, photo_id, option, category_id) values ( 'id mauris', 'amet lobortis sapien sapien non', 78, null, 9);
insert into product ( title, description, photo_id, option, category_id) values ( 'sem mauris laoreet', null, null, null, 11);
insert into product ( title, description, photo_id, option, category_id) values ( 'faucibus orci luctus', null, null, null, 3);
insert into product ( title, description, photo_id, option, category_id) values ( 'suspendisse potenti', 'id ornare imperdiet sapien urna pretium', 8, null, 20);
insert into product ( title, description, photo_id, option, category_id) values ( 'congue', null, null, null, 20);
insert into product ( title, description, photo_id, option, category_id) values ( 'suspendisse', 'dui proin leo odio porttitor id consequat in', 64, null, 19);
insert into product ( title, description, photo_id, option, category_id) values ( 'volutpat quam', null, null, null, 10);
insert into product ( title, description, photo_id, option, category_id) values ( 'accumsan tortor', 'ligula nec sem duis aliquam convallis nunc proin at', 5, null, 18);
insert into product ( title, description, photo_id, option, category_id) values ( 'vestibulum vestibulum', 'quis turpis sed ante vivamus tortor duis mattis egestas', 98, null, 15);
insert into product ( title, description, photo_id, option, category_id) values ( 'mauris', 'ullamcorper augue', 23, null, 17);
insert into product ( title, description, photo_id, option, category_id) values ( 'in', 'dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum', 36, null, 17);
insert into product ( title, description, photo_id, option, category_id) values ( 'justo', 'in est', 79, null, 2);
insert into product ( title, description, photo_id, option, category_id) values ( 'eros vestibulum', 'condimentum curabitur in libero', 14, null, 16);
insert into product ( title, description, photo_id, option, category_id) values ( 'sagittis dui vel', null, null, null, 5);
insert into product ( title, description, photo_id, option, category_id) values ( 'lorem', null, null, null, 3);
insert into product ( title, description, photo_id, option, category_id) values ( 'posuere felis sed', 'diam neque vestibulum eget vulputate ut ultrices', 29, null, 20);
insert into product ( title, description, photo_id, option, category_id) values ( 'cubilia', 'et magnis dis', 19, null, 17);
insert into product ( title, description, photo_id, option, category_id) values ( 'dapibus dolor vel', 'vestibulum vestibulum ante ipsum', 20, null, 8);
insert into product ( title, description, photo_id, option, category_id) values ( 'potenti in', null, null, null, 1);
insert into product ( title, description, photo_id, option, category_id) values ( 'mi', 'sit amet turpis elementum ligula vehicula consequat', 26, null, 4);
insert into product ( title, description, photo_id, option, category_id) values ( 'nullam sit amet', 'eros vestibulum ac est lacinia', 58, null, 16);
insert into product ( title, description, photo_id, option, category_id) values ( 'commodo placerat praesent', 'nullam orci pede venenatis non sodales sed tincidunt eu felis', 28, null, 20);
insert into product ( title, description, photo_id, option, category_id) values ( 'sed', 'et ultrices posuere cubilia curae duis faucibus', 49, null, 15);
insert into product ( title, description, photo_id, option, category_id) values ( 'sit amet', null, null, null, 2);
insert into product ( title, description, photo_id, option, category_id) values ( 'id mauris', 'aliquet at feugiat non pretium quis lectus suspendisse', 45, null, 18);
insert into product ( title, description, photo_id, option, category_id) values ( 'nulla', null, null, null, 18);
insert into product ( title, description, photo_id, option, category_id) values ( 'nisi', 'lorem integer', 47, null, 15);
insert into product ( title, description, photo_id, option, category_id) values ( 'rhoncus aliquet', 'luctus et', 14, null, 18);
insert into product ( title, description, photo_id, option, category_id) values ( 'consequat ut nulla', 'duis consequat dui nec nisi volutpat eleifend donec ut', 66, null, 5);
insert into product ( title, description, photo_id, option, category_id) values ( 'commodo placerat', null, null, null, 15);
insert into product ( title, description, photo_id, option, category_id) values ( 'nibh in lectus', null, null, null, 17);
insert into product ( title, description, photo_id, option, category_id) values ( 'massa', null, null, null, 13);
insert into product ( title, description, photo_id, option, category_id) values ( 'sed interdum venenatis', 'venenatis lacinia aenean sit amet justo morbi ut odio', 67, null, 20);
insert into product ( title, description, photo_id, option, category_id) values ( 'blandit ultrices enim', null, null, null, 3);
insert into product ( title, description, photo_id, option, category_id) values ( 'lacus', 'nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel', 70, null, 17);
insert into product ( title, description, photo_id, option, category_id) values ( 'in quis', null, null, null, 9);
insert into product ( title, description, photo_id, option, category_id) values ( 'nulla mollis molestie', 'sit amet consectetuer adipiscing', 41, null, 3);
insert into product ( title, description, photo_id, option, category_id) values ( 'amet', null, null, null, 6);
insert into product ( title, description, photo_id, option, category_id) values ( 'urna pretium', null, null, null, 11);
insert into product ( title, description, photo_id, option, category_id) values ( 'feugiat non', null, null, null, 3);
insert into product ( title, description, photo_id, option, category_id) values ( 'habitasse platea', 'semper est quam pharetra magna ac', 85, null, 8);
insert into product ( title, description, photo_id, option, category_id) values ( 'nulla', null, null, null, 15);
insert into product ( title, description, photo_id, option, category_id) values ( 'elementum nullam varius', 'rhoncus mauris enim leo rhoncus sed vestibulum sit amet', 94, null, 3);
insert into product ( title, description, photo_id, option, category_id) values ( 'integer a nibh', 'suspendisse ornare consequat lectus in', 70, null, 16);
insert into product ( title, description, photo_id, option, category_id) values ( 'sollicitudin', 'metus aenean fermentum donec ut mauris', 95, null, 10);
insert into product ( title, description, photo_id, option, category_id) values ( 'urna pretium', 'in hac habitasse platea dictumst morbi vestibulum velit', 27, null, 5);
insert into product ( title, description, photo_id, option, category_id) values ( 'eros vestibulum ac', null, null, null, 13);
insert into product ( title, description, photo_id, option, category_id) values ( 'maecenas tristique', 'ipsum aliquam non mauris morbi non lectus aliquam sit amet', 27, null, 12);
insert into product ( title, description, photo_id, option, category_id) values ( 'ac nulla sed', null, null, null, 8);
insert into product ( title, description, photo_id, option, category_id) values ( 'vitae nisi', 'magna ac consequat metus sapien ut nunc vestibulum', 83, null, 6);
insert into product ( title, description, photo_id, option, category_id) values ( 'cubilia', 'sed augue', 56, null, 1);
insert into product ( title, description, photo_id, option, category_id) values ( 'ornare imperdiet sapien', null, null, null, 14);
insert into product ( title, description, photo_id, option, category_id) values ( 'tortor', 'consequat nulla nisl nunc nisl duis bibendum', 64, null, 3);
insert into product ( title, description, photo_id, option, category_id) values ( 'tristique est', 'magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit', 78, null, 15);
insert into product ( title, description, photo_id, option, category_id) values ( 'mi integer ac', null, null, null, 15);
insert into product ( title, description, photo_id, option, category_id) values ( 'vulputate elementum', 'ante vivamus tortor duis mattis egestas metus aenean fermentum', 43, null, 6);
insert into product ( title, description, photo_id, option, category_id) values ( 'fermentum justo', null, null, null, 11);
insert into product ( title, description, photo_id, option, category_id) values ( 'eget', null, null, null, 5);
insert into product ( title, description, photo_id, option, category_id) values ( 'morbi sem mauris', null, null, null, 18);
insert into product ( title, description, photo_id, option, category_id) values ( 'mauris', null, null, null, 9);




insert into accounting_product ( product_id, amount, price) values (1, 59, 5188);
insert into accounting_product ( product_id, amount, price) values (2, 39, 8846);
insert into accounting_product ( product_id, amount, price) values (3, 73, 9450);
insert into accounting_product ( product_id, amount, price) values (4, 87, 592);
insert into accounting_product ( product_id, amount, price) values (5, 68, 3706);
insert into accounting_product ( product_id, amount, price) values (6, 60, 1814);
insert into accounting_product ( product_id, amount, price) values (7, null, 4520);
insert into accounting_product ( product_id, amount, price) values (8, 52, 5328);
insert into accounting_product ( product_id, amount, price) values (9, 46, 4339);
insert into accounting_product ( product_id, amount, price) values ( 10, null, 6305);
insert into accounting_product ( product_id, amount, price) values ( 11, null, 7180);
insert into accounting_product ( product_id, amount, price) values ( 12, null, 169);
insert into accounting_product ( product_id, amount, price) values ( 13, 93, 6298);
insert into accounting_product ( product_id, amount, price) values ( 14, null, 1701);
insert into accounting_product ( product_id, amount, price) values ( 15, 24, 5575);
insert into accounting_product ( product_id, amount, price) values ( 16, 38, 1887);
insert into accounting_product ( product_id, amount, price) values ( 17, null, 532);
insert into accounting_product ( product_id, amount, price) values ( 18, 102, 9167);
insert into accounting_product ( product_id, amount, price) values ( 19, 89, 8327);
insert into accounting_product ( product_id, amount, price) values ( 20, 15, 4273);
insert into accounting_product ( product_id, amount, price) values ( 21, null, 3058);
insert into accounting_product ( product_id, amount, price) values ( 22, 117, 2113);
insert into accounting_product ( product_id, amount, price) values ( 23, 24, 5744);
insert into accounting_product ( product_id, amount, price) values ( 24, null, 8829);
insert into accounting_product ( product_id, amount, price) values ( 25, 82, 7557);
insert into accounting_product ( product_id, amount, price) values ( 26, 28, 3150);
insert into accounting_product ( product_id, amount, price) values ( 27, 5, 5532);
insert into accounting_product ( product_id, amount, price) values ( 28, 32, 444);
insert into accounting_product ( product_id, amount, price) values ( 29, 117, 3428);
insert into accounting_product ( product_id, amount, price) values ( 30, 106, 9464);
insert into accounting_product ( product_id, amount, price) values ( 31, null, 9113);
insert into accounting_product ( product_id, amount, price) values ( 32, null, 8188);
insert into accounting_product ( product_id, amount, price) values ( 33, 80, 9568);
insert into accounting_product ( product_id, amount, price) values ( 34, null, 4767);
insert into accounting_product ( product_id, amount, price) values ( 35, null, 1771);
insert into accounting_product ( product_id, amount, price) values ( 36, 91, 8710);
insert into accounting_product ( product_id, amount, price) values ( 37, 5, 2749);
insert into accounting_product ( product_id, amount, price) values ( 38, 21, 1958);
insert into accounting_product ( product_id, amount, price) values ( 39, 45, 2130);
insert into accounting_product ( product_id, amount, price) values ( 40, 5, 498);
insert into accounting_product ( product_id, amount, price) values ( 41, 2, 1609);
insert into accounting_product ( product_id, amount, price) values ( 42, 61, 7809);
insert into accounting_product ( product_id, amount, price) values ( 43, 112, 1356);
insert into accounting_product ( product_id, amount, price) values ( 44, null, 4085);
insert into accounting_product ( product_id, amount, price) values ( 45, null, 57);
insert into accounting_product ( product_id, amount, price) values ( 46, 60, 3039);
insert into accounting_product ( product_id, amount, price) values ( 47, 96, 8719);
insert into accounting_product ( product_id, amount, price) values ( 48, 93, 1336);
insert into accounting_product ( product_id, amount, price) values ( 49, 99, 4345);
insert into accounting_product ( product_id, amount, price) values ( 50, null, 6688);
insert into accounting_product ( product_id, amount, price) values ( 51, 116, 6097);
insert into accounting_product ( product_id, amount, price) values ( 52, 110, 6321);
insert into accounting_product ( product_id, amount, price) values ( 53, null, 9519);
insert into accounting_product ( product_id, amount, price) values ( 54, 45, 3858);
insert into accounting_product ( product_id, amount, price) values ( 55, 47, 351);
insert into accounting_product ( product_id, amount, price) values ( 56, null, 5031);
insert into accounting_product ( product_id, amount, price) values ( 57, null, 297);
insert into accounting_product ( product_id, amount, price) values ( 58, 75, 9058);
insert into accounting_product ( product_id, amount, price) values ( 59, null, 9880);
insert into accounting_product ( product_id, amount, price) values ( 60, 54, 7337);
insert into accounting_product ( product_id, amount, price) values ( 61, 2, 8727);
insert into accounting_product ( product_id, amount, price) values ( 62, 61, 7113);
insert into accounting_product ( product_id, amount, price) values ( 63, 64, 1001);
insert into accounting_product ( product_id, amount, price) values ( 64, 34, 7686);
insert into accounting_product ( product_id, amount, price) values ( 65, null, 5234);
insert into accounting_product ( product_id, amount, price) values ( 66, 98, 4606);
insert into accounting_product ( product_id, amount, price) values ( 67, null, 459);
insert into accounting_product ( product_id, amount, price) values ( 68, 98, 5079);
insert into accounting_product ( product_id, amount, price) values ( 69, 90, 5053);
insert into accounting_product ( product_id, amount, price) values ( 70, 76, 152);
insert into accounting_product ( product_id, amount, price) values ( 71, 120, 1415);
insert into accounting_product ( product_id, amount, price) values ( 72, 62, 9586);
insert into accounting_product ( product_id, amount, price) values ( 73, 32, 7168);
insert into accounting_product ( product_id, amount, price) values ( 74, 4, 6856);
insert into accounting_product ( product_id, amount, price) values ( 75, 65, 7068);
insert into accounting_product ( product_id, amount, price) values ( 76, 91, 4751);
insert into accounting_product ( product_id, amount, price) values ( 77, 12, 9765);
insert into accounting_product ( product_id, amount, price) values ( 78, 97, 7611);
insert into accounting_product ( product_id, amount, price) values ( 79, 28, 4162);
insert into accounting_product ( product_id, amount, price) values ( 80, 64, 5457);
insert into accounting_product ( product_id, amount, price) values ( 81, 23, 1247);
insert into accounting_product ( product_id, amount, price) values ( 82, null, 8215);
insert into accounting_product ( product_id, amount, price) values ( 83, null, 3787);
insert into accounting_product ( product_id, amount, price) values ( 84, 41, 426);
insert into accounting_product ( product_id, amount, price) values ( 85, 101, 1339);
insert into accounting_product ( product_id, amount, price) values ( 86, 67, 9831);
insert into accounting_product ( product_id, amount, price) values ( 87, 108, 696);
insert into accounting_product ( product_id, amount, price) values ( 88, 79, 2258);
insert into accounting_product ( product_id, amount, price) values ( 89, 72, 6469);
insert into accounting_product ( product_id, amount, price) values ( 90, 102, 2667);
insert into accounting_product ( product_id, amount, price) values ( 91, null, 9112);
insert into accounting_product ( product_id, amount, price) values ( 92, 73, 4727);
insert into accounting_product ( product_id, amount, price) values ( 93, 58, 9132);
insert into accounting_product ( product_id, amount, price) values ( 94, 76, 5053);
insert into accounting_product ( product_id, amount, price) values ( 95, 106, 6333);
insert into accounting_product ( product_id, amount, price) values ( 96, 109, 7270);
insert into accounting_product ( product_id, amount, price) values ( 97, 68, 8907);
insert into accounting_product ( product_id, amount, price) values ( 98, 52, 3807);
insert into accounting_product ( product_id, amount, price) values ( 99, 26, 8951);
insert into accounting_product ( product_id, amount, price) values ( 100, 35, 1272);
insert into accounting_product ( product_id, amount, price) values ( 101, 71, 1386);
insert into accounting_product ( product_id, amount, price) values ( 102, 25, 5715);
insert into accounting_product ( product_id, amount, price) values ( 103, 48, 9650);
insert into accounting_product ( product_id, amount, price) values ( 104, 73, 7449);
insert into accounting_product ( product_id, amount, price) values ( 105, 83, 4759);
insert into accounting_product ( product_id, amount, price) values ( 106, null, 8911);
insert into accounting_product ( product_id, amount, price) values ( 107, 92, 3903);
insert into accounting_product ( product_id, amount, price) values ( 108, 18, 7068);
insert into accounting_product ( product_id, amount, price) values ( 109, 71, 427);
insert into accounting_product ( product_id, amount, price) values ( 110, 112, 9092);
insert into accounting_product ( product_id, amount, price) values ( 111, 119, 2592);
insert into accounting_product ( product_id, amount, price) values ( 112, 76, 326);
insert into accounting_product ( product_id, amount, price) values ( 113, 83, 1602);
insert into accounting_product ( product_id, amount, price) values ( 114, null, 6237);
insert into accounting_product ( product_id, amount, price) values ( 115, null, 4641);
insert into accounting_product ( product_id, amount, price) values ( 116, 17, 7879);
insert into accounting_product ( product_id, amount, price) values ( 117, 52, 9032);
insert into accounting_product ( product_id, amount, price) values ( 118, 7, 9453);
insert into accounting_product ( product_id, amount, price) values ( 119, null, 2760);
insert into accounting_product ( product_id, amount, price) values ( 120, 35, 5622);
insert into accounting_product ( product_id, amount, price) values ( 121, 19, 7505);
insert into accounting_product ( product_id, amount, price) values ( 122, 43, 4780);
insert into accounting_product ( product_id, amount, price) values ( 123, 97, 6260);
insert into accounting_product ( product_id, amount, price) values ( 124, 33, 6788);
insert into accounting_product ( product_id, amount, price) values ( 125, 4, 7067);
insert into accounting_product ( product_id, amount, price) values ( 126, 54, 7386);
insert into accounting_product ( product_id, amount, price) values ( 127, null, 3643);
insert into accounting_product ( product_id, amount, price) values ( 128, 77, 4600);
insert into accounting_product ( product_id, amount, price) values ( 129, 45, 6483);
insert into accounting_product ( product_id, amount, price) values ( 130, 50, 359);
insert into accounting_product ( product_id, amount, price) values ( 131, 95, 6879);
insert into accounting_product ( product_id, amount, price) values ( 132, 66, 8698);
insert into accounting_product ( product_id, amount, price) values ( 133, 63, 9841);
insert into accounting_product ( product_id, amount, price) values ( 134, 117, 7533);
insert into accounting_product ( product_id, amount, price) values ( 135, 27, 4942);
insert into accounting_product ( product_id, amount, price) values ( 136, 116, 5602);
insert into accounting_product ( product_id, amount, price) values ( 137, 90, 6889);
insert into accounting_product ( product_id, amount, price) values ( 138, 78, 1961);
insert into accounting_product ( product_id, amount, price) values ( 139, 32, 6416);
insert into accounting_product ( product_id, amount, price) values ( 140, null, 8607);
insert into accounting_product ( product_id, amount, price) values ( 141, 40, 9569);
insert into accounting_product ( product_id, amount, price) values ( 142, 96, 6315);
insert into accounting_product ( product_id, amount, price) values ( 143, 38, 1529);
insert into accounting_product ( product_id, amount, price) values ( 144, null, 1373);
insert into accounting_product ( product_id, amount, price) values ( 145, 89, 950);
insert into accounting_product ( product_id, amount, price) values ( 146, 76, 8635);
insert into accounting_product ( product_id, amount, price) values ( 147, 21, 531);
insert into accounting_product ( product_id, amount, price) values ( 148, 74, 9716);
insert into accounting_product ( product_id, amount, price) values ( 149, null, 2923);
insert into accounting_product ( product_id, amount, price) values ( 150, 119, 7447);
